# Generated by Django 5.0.1 on 2024-09-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='content',
            name='quiz_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
