# Generated by Django 5.0.1 on 2024-09-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_remove_content_quiz_id_content_quiz_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
