# Generated by Django 5.1.1 on 2024-10-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_usersettings_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='suscribed',
            field=models.BooleanField(default=False),
        ),
    ]
