# Generated by Django 5.0.1 on 2024-09-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_alter_content_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
