# Generated by Django 5.1.1 on 2024-10-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=12, unique=True),
        ),
    ]
